# Generated by Django 4.2.9 on 2024-01-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('attachement', models.FileField(upload_to='attachments/')),
                ('views', models.IntegerField()),
            ],
        ),
    ]
