# Generated by Django 4.2.9 on 2024-01-03 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='attachement',
            new_name='attachment',
        ),
    ]
