# Generated by Django 4.2.9 on 2024-01-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_rename_attachement_board_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
