# Generated by Django 4.2.9 on 2024-01-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_alter_board_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
